name: Caliary Client CI

on:
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        pnpm-version: [8.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version:  ${{ matrix.node-version }}

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: ${{ matrix.pnpm-version }}

    - name: Install dependencies
      run: pnpm install

    - name: Check Lint
      run: pnpm lint

    - name: Build
      run: pnpm build
